[theme]
primaryColor = "#2563EB"
backgroundColor = "#F9FAFB" 
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1F2937"
font = "sans serif"

[server]
port = 8080
address = "0.0.0.0"
headless = true
enableCORS = true  # Must be true when enableXsrfProtection=true
enableXsrfProtection = true  # Security feature

[browser]
serverAddress = "0.0.0.0"
gatherUsageStats = false
