[theme]
# Professional Blue Palette
primaryColor="#2563EB" # Action Blue
backgroundColor="#F9FAFB" # Light Cool Grey Background
secondaryBackgroundColor="#FFFFFF" # White for containers/cards
textColor="#1F2937" # Dark Slate Grey Text
font="sans serif" # Standard sans-serif font
[server]
port = 8080
address = "0.0.0.0"
headless = true
enableCORS = false
enableXsrfProtection = true
[browser]
serverAddress = "0.0.0.0"
gatherUsageStats = false
